"""empty message

Revision ID: f80a9a0e66d2
Revises: 4acc55c6f7ef
Create Date: 2023-02-09 00:23:33.591940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f80a9a0e66d2'
down_revision = '4acc55c6f7ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('active')
        batch_op.drop_column('lastlogin')
        batch_op.drop_column('validationcode')
        batch_op.drop_column('username')
        batch_op.drop_column('comments')
        batch_op.drop_column('datejoined')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datejoined', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('comments', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('validationcode', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('lastlogin', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
